package com.georgemcarlson.jbasen;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import static org.junit.Assert.*;
import org.junit.Test;

public class ExpectedEncodingResultsTest {
    private static final Map<String,byte[]> DICTIONARY_TO_ENCODED_DATA = new HashMap();
    static{
        DICTIONARY_TO_ENCODED_DATA.put("ABC", "BAAABAABBAAABAABBBBAABBAABBAAABBBABBABBBAAABABAABBABABBBBBBBABBBBABABBABBBAAABAAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCD", "ABAABBAAABBACBCAABBAAAABACAAABABBCBABABABBABACBABAABBBCABCCAAACAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDE", "ABCACBABCDCACBCBCBCBCCDBBBAACDDADDDBCBBACBCBABAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEF", "BCBAAECABEBACAEACAEACEEAABAACCCACAABCEAACAEAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFG", "CDAACFDABBFAADBADADAFEBAFDCABDDADBBADBEAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGH", "EDAABABAEECBBCABFGCBDFBAGACBABGAFBGAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHI", "CCBADBDAFBDBHFBBFAEAHGHADBHBBDGAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJ", "BABAFECAGHIACGHAACDAIBGAIICBEAFAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJK", "CIAADACAHBHADCGABGCADAFABHJAJAEAAAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKL", "EKCAAIGAFGCBJHDBKEBADHBBHABBEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLM", "IFCAKHFAAFLAEEABHCBAIHKAHBKAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMN", "AAIAJDGBMBFAFBKBGAJALMJBBIDA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNO", "IMGALICBCGEANMFBBLHAHLFBKBDA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOP", "CAGAEHOAANDAFFCBMLGAAECBMKCA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQ", "BJEAMOCBHDLBFBEBOPOBGGLAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQR", "NAEAQMQAOBHBHNABMHKBLBKAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRS", "RKDACROABJDBLPPAOIGBCAJAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRST", "KEDASHNANFABLEOALSCBLBIAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTU", "JSCAECMAHIRABRMAOQTASFHAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUV", "JMOANQGAQTOAPQAAMJSATODA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVW", "LGNADEGALNNAVPAAVRQAIIDA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWX", "SDMAFPFALKMAGPAAUIPADCDA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXY", "DELATEFANKLAPOAADDOAEUCA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "KHKAUTEAONKABOAAOANALPCA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZa", "CMLAVSRACNDBHIIAOZTBWDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZab", "BRKAULQASJABHTHAHRPBTDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabc", "WYJAZHPAIMZAXEHAESLBQDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcd", "HGJAEHOAVUXAaTGAZbHBNDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcde", "KSIALJNAYEWANHGAEQEBKDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef", "ACIAPOMALXUAMaFAWKBBHDAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefg", "GSDAbMXAAdNAfdLBMWFBEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh", "YLDAFAWARCNAMKIBbOCBEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi", "QFDAbYUAcKMAJfEBONhAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij", "OiCAXTTAeVLAQZBBiRfAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk", "SdCAXRSAUjKAbZiAMcdAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl", "cYCAYSRAgOKAkfgANHcAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklm", "GUCAXWQAcgJAlFfAibaAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmn", "bPCARdPAFOJAYWdAhOZAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmno", "OLCADnOAAkIAfEcAEFYAEAAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop", "bnSAjAQBbfaBMPmAZLIA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopq", "GDSAIOMBVYWBjXkAWlHA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqr", "VKRAFkIBSaSBFmiAjWHA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrs", "cUQAUWFBJlOBBOhAUIHA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrst", "YhPACPCBeLLBUmfATnGA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu", "GDPAiNtAdmHBNWeAgaGA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuv", "SUOATSrAsaEBVJdAMOGA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvw", "MoNAscpAVVBBpvbAECGA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx", "iNNAItnAAWvAVqaAInFA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy", "ilMACRmAZctAFoZAYcFA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", "GLSAofuAVCwAmWrBEgAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0", "NbRADssAPLuAGsmBYfAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01", "DuQADJrAyZsA0XiBueAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012", "bNQAlfpAPuqAINeBQeAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123", "ekPAvEoALRpAYLaBpdAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234", "JGPAblmAjvnAmSWBMdAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345", "ShOAcSlAbamApiSBocAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456", "5EOAvCkAnIlAYBPBMcAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567", "IkNAWxiAJ1jAlhLBrbAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345678", "tJNAHphAzqiAOOIBQbAA".getBytes());
        DICTIONARY_TO_ENCODED_DATA.put("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "xsMA8jgArjhAHBFByaAA".getBytes());
    }
    
    @Test
    public void runQuery() throws Exception {
        byte[] message = "Hello World".getBytes();
        for(String dictionary : DICTIONARY_TO_ENCODED_DATA.keySet()){
            byte[] expectedEncodedData = DICTIONARY_TO_ENCODED_DATA.get(dictionary);
            byte[] encodedData = BaseN.getInstance(dictionary.getBytes()).encode(message);
            byte[] decodedData = BaseN.getInstance(dictionary.getBytes()).decode(encodedData);

            System.out.println(dictionary);
            System.out.println(StreamReader.read(encodedData));
            System.out.println(StreamReader.read(decodedData));
            System.out.println("-----------------------------------------");

            if(!Arrays.equals(expectedEncodedData,encodedData)){
                fail();
            }
            if(!Arrays.equals(message,decodedData)){
                fail();
            }
        }
    }
}